### ISSUE TITLE
NoClassDefFoundError: org/apache/hadoop/hive/ql/session/SessionState when creating Hive client using classpath

### ISSUE THREAD

**Issue by geoHeil** [holdenk/spark-testing-base#266]
Hive dependencies seem to no longer be loaded. This issue only occurred as of yesterday after upgrading the JDK to 1.8.0_192

I have created an reproducible problem:
https://github.com/geoHeil/classpath-gradle-test-failures

```
git clone git@github.com:geoHeil/classpath-gradle-test-failures.git
cd classpath-gradle-test-failure
./gradlew test
```

**Comment by geoHeil** [comment]
this behavior occurs if accidentally Jak > 8 is used
