### PR TITLE
Update Spark version to 2.4.0

### LINKED ISSUE #270: Spark 2.4.0 Release
Spark version 2.4.0 has been released recently and with this release Scala 2.12.x versions can be used for writing Spark apps.

It would be great to compile spark-testing-base with Spark 2.4.0 version.

### PR DESCRIPTION
**Pull request by morazow**
This only updates the Spark version to 2.4.0.

I also tried to compile with Scala 2.12.7; however, there were some compilation errors related to `SharedJavaSparkContext` and `SparkContextProvider`. 

Fixes #270

### CODE REVIEW

**Comment by dbast** [comment]
+1

Seems like you also need to add the version to the build/release matrix here https://github.com/holdenk/spark-testing-base/blob/master/mini-cross-build.pl#L5

(After compiling for 2.12 works, this script most probably needs another extension.)

**Comment by dbast** [comment]
Hi @morazow, good to see you :) Should do that in rl at times :)

**Comment by MuqadderIqbal** [comment]
Hey guys, when will this update be publicly available? I currently run Spark 2.4.0 with Scala 2.11.12 and the sample project based on holdenk/sparkProjectTemplate.g8 template fails tests in sbt/IntelliJ.

**Comment by morazow** [comment]
Hello @holdenk ,

Let me know your feedback :)

If everything looks good, could you please merge and release?

**Comment by MuqadderIqbal** [comment]
Thanks for the quick turn-around, everyone! Much appreciated! Will the sample g8 project automatically pull this new version after it gets published? Or do I need to modify the build.sbt file to specify the new version? If so, what version of this library supports Spark 2.4.0? Thanks for all the good work once again!
