### ISSUE TITLE
Undefined Hive function error while using the Spark 2 testing framework

### ISSUE THREAD

**Issue by himanishk** [holdenk/spark-testing-base#140]
Hi,

I am getting this error while executing a test case - `org.apache.spark.sql.AnalysisException: Undefined function: 'percentile'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'`

I am using `DataFrameSuiteBase` from `"com.holdenkarau" %% "spark-testing-base" % "2.0.0_0.4.5"`

The code being tested registers a temporary view `abotp` and then issues the following SQL - 

```
sparkSession.sql("select id,percentile(max_time,0.70) as ptile from abotp group by id")
```

Does the SQLContext from `DataFrameSuiteBase` not support Hive functions ? This used to work fine with Spark 1.6 and the `"com.holdenkarau" %% "spark-testing-base" % "1.6.0_0.3.0"`

Could you please advise.

Thanks

**Comment by samudurand** [comment]
@himanishk I am interested in testing with Spark2 also, could you tell me how you obtained a sparkSession with SparkTestingBase ? All I can see in the basic Trait is a SparkContext

**Comment by samudurand** [comment]
Ah forget my question, I found the necessary Base . I got the same issue as you. 

````
A needed class was not found. This could be due to an error in your runpath. Missing class: org/apache/hadoop/hive/conf/HiveConf$ConfVars
java.lang.NoClassDefFoundError: org/apache/hadoop/hive/conf/HiveConf$ConfVars
````

**Comment by holdenk** [comment]
That's a good question, for `0.6` I've made the suite base use `SparkSession` and automatically attempt to enable hive support (if the jars are present).

**Comment by artyomboyko** [comment]
Same issue

**Comment by holdenk** [comment]
I'm going to go ahead and close this issue since 0.6 is released - if anyone encounter this in 0.6+ please feel free to re-open :)
